version: '3.8'

services:
  watcher_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # 데이터베이스 파일 마운트
      - ./db:/app/db
    env_file:
      - .env