

services:
  watcher:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      # 코드 서버 디렉토리 마운트 (읽기 전용)
      - /home/ubuntu/jcode:/watcher/codes:ro
      # 스냅샷 저장소 마운트
      - ./snapshots:/watcher/snapshots
      - ./src/:/app/src/
