version: '3.8'

services:
  watcher:
    build:
      context: .
      dockerfile: Dockerfile
    image: watcher-proc:latest
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    pid: host
    volumes:
      - ./src:/app/src
      - /sys/kernel/debug:/sys/kernel/debug:ro
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
    environment:
      - PYTHONUNBUFFERED=1