# os-1-202012180 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-1-202012180
  labels:
    app: os-1-202012180
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os-1-202012180
  template:
    metadata:
      labels:
        app: os-1-202012180
    spec:
      containers:
      - name: os-1-202012180
        image: codercom/code-server:4.96.4-ubuntu
        ports:
        - containerPort: 8080
        env:
        - name: PASSWORD
          value: "testpass"
        - name: SUDO_PASSWORD
          value: "testpass"
        volumeMounts:
        - name: workspace-volume
          mountPath: /home/coder/project
      volumes:
      - name: workspace-volume
        hostPath:
          path: /watcher/codes/os-1-202012180/
          type: Directory

---
# os-1-202012180 Service
apiVersion: v1
kind: Service
metadata:
  name: os-1-202012180
spec:
  type: LoadBalancer
  selector:
    app: os-1-202012180
  ports:
  - port: 8080
    targetPort: 8080

---
# ai-3-202012180 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-3-202012180
  labels:
    app: ai-3-202012180
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-3-202012180
  template:
    metadata:
      labels:
        app: ai-3-202012180
    spec:
      containers:
      - name: ai-3-202012180
        image: codercom/code-server:4.96.4-ubuntu
        ports:
        - containerPort: 8080
        env:
        - name: PASSWORD
          value: "testpass"
        - name: SUDO_PASSWORD
          value: "testpass"
        volumeMounts:
        - name: workspace-volume
          mountPath: /home/coder/project
      volumes:
      - name: workspace-volume
        hostPath:
          path: /watcher/codes/ai-3-202012180/
          type: Directory

---
# ai-3-202012180 Service
apiVersion: v1
kind: Service
metadata:
  name: ai-3-202012180
spec:
  type: LoadBalancer
  selector:
    app: ai-3-202012180
  ports:
  - port: 8080
    targetPort: 8080

