apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: watcher-code
  namespace: watcher
spec:
  selector:
    matchLabels:
      app: watcher-code
  template:
    metadata:
      labels:
        app: watcher-code
    spec:
      containers:
      - name: watcher-code
        image: watcher-code:1  # 미리 빌드된 이미지 사용
        imagePullPolicy: IfNotPresent  # 이미지가 존재하지 않을 때만 가져옴
        volumeMounts:
        - name: jcode-vol
          mountPath: /watcher/codes
          readOnly: true
        env:
        - name: WATCHER_LOG_LEVEL
          value: "DEBUG"
        - name: WATCHER_API_URL
          value: "http://172.0.0.1:8080"
      volumes:
      - name: jcode-vol
        nfs:
          server: "#"
          path: "#"
  