apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: watcher-proc
  namespace: watcher
spec:
  selector:
    matchLabels:
      app: watcher-proc
  template:
    metadata:
      labels:
        app: watcher-proc
    spec:
      serviceAccountName: watcher-proc-sa  # ServiceAccount 이름 수정
      hostPID: true  # 호스트 PID 네임스페이스 접근
      containers:
      - name: watcher-proc
        image: watcher-proc:latest
        imagePullPolicy: IfNotPresent  # 로컬 이미지 사용
        securityContext:
          capabilities:
            drop: ["ALL"]
            add: ["SYS_ADMIN", "SYS_PTRACE"]  # 필요한 capabilities만 추가
        volumeMounts:
        - name: kernel-modules
          mountPath: /lib/modules
          readOnly: true
        - name: kernel-src
          mountPath: /usr/src
          readOnly: true
        - name: kernel-debug
          mountPath: /sys/kernel/debug
          readOnly: true
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: proc
          mountPath: /proc
      volumes:
      - name: kernel-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: kernel-src
        hostPath:
          path: /usr/src
          type: Directory
      - name: kernel-debug
        hostPath:
          path: /sys/kernel/debug
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      - name: proc
        hostPath:
          path: /proc
          type: Directory

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher-proc-sa  # ServiceAccount 이름 수정
  namespace: watcher
---
# 테스트 환경용 ClusterRole (모든 네임스페이스 접근)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watcher-proc-role  # Role 이름 수정
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
# 테스트 환경용 ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: watcher-proc-binding  # Binding 이름 수정
subjects:
- kind: ServiceAccount
  name: watcher-proc-sa  # ServiceAccount 참조 수정
  namespace: watcher
roleRef:
  kind: ClusterRole
  name: watcher-proc-role  # Role 참조 수정
  apiGroup: rbac.authorization.k8s.io
---
# 프로덕션 환경용 Role과 RoleBinding (기본적으로 주석 처리)
# jcode-ai-4 네임스페이스용 Role
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: watcher-proc-role  # Role 이름 수정
#   namespace: jcode-ai-4
# rules:
# - apiGroups: [""]
#   resources: ["pods"]
#   verbs: ["get", "list", "watch"]
# ---
# jcode-ai-4 네임스페이스용 RoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: watcher-proc-binding  # Binding 이름 수정
#   namespace: jcode-ai-4
# subjects:
# - kind: ServiceAccount
#   name: watcher-proc-sa  # ServiceAccount 참조 수정
#   namespace: watcher
# roleRef:
#   kind: Role
#   name: watcher-proc-role  # Role 참조 수정
#   apiGroup: rbac.authorization.k8s.io
# ---
# jcode-os-5 네임스페이스용 Role
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: watcher-proc-role  # Role 이름 수정
#   namespace: jcode-os-5
# rules:
# - apiGroups: [""]
#   resources: ["pods"]
#   verbs: ["get", "list", "watch"]
# ---
# jcode-os-5 네임스페이스용 RoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: watcher-proc-binding  # Binding 이름 수정
#   namespace: jcode-os-5
# subjects:
# - kind: ServiceAccount
#   name: watcher-proc-sa  # ServiceAccount 참조 수정
#   namespace: watcher
# roleRef:
#   kind: Role
#   name: watcher-proc-role  # Role 참조 수정
#   apiGroup: rbac.authorization.k8s.io
