apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: watcher-proc
  namespace: watcher
spec:
  selector:
    matchLabels:
      app: watcher-proc
  template:
    metadata:
      labels:
        app: watcher-proc
    spec:
      hostPID: true  # 호스트 PID 네임스페이스 접근
      containers:
      - name: watcher-proc
        image: watcher-proc:latest
        imagePullPolicy: IfNotPresent  # 로컬 이미지 사용
        ports:
        - name: http-metrics
          containerPort: 9090
        env:
        - name: API_ENDPOINT
          value: "http://watcher-backend-service.watcher.svc.cluster.local:3000"  # API 서비스 엔드포인트
        - name: LOG_LEVEL
          value: "INFO"  # 로그 레벨 설정
        securityContext:
          capabilities:
            drop: ["ALL"]
            add: ["SYS_ADMIN", "SYS_PTRACE"]  # 필요한 capabilities만 추가
        volumeMounts:
        - name: kernel-modules
          mountPath: /lib/modules
          readOnly: true
        - name: kernel-src
          mountPath: /usr/src
          readOnly: true
        - name: kernel-debug
          mountPath: /sys/kernel/debug
          readOnly: true
      volumes:
      - name: kernel-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: kernel-src
        hostPath:
          path: /usr/src
          type: Directory
      - name: kernel-debug
        hostPath:
          path: /sys/kernel/debug
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: watcher-proc
  namespace: watcher
  labels:
    app: watcher-proc
spec:
  selector:
    app: watcher-proc
  ports:
  - name: http-metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
                   