apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: watcher-code
  namespace: watcher
spec:
  selector:
    matchLabels:
      app: watcher-code
  template:
    metadata:
      labels:
        app: watcher-code
    spec:
      containers:
      - name: watcher-code
        image: watcher-code:latest  # 미리 빌드된 이미지 사용
        imagePullPolicy: IfNotPresent  # 이미지가 존재하지 않을 때만 가져옴
        ports:
        - name: http-metrics
          containerPort: 9090
        volumeMounts:
        - name: jcode-vol
          mountPath: /watcher/codes
          subPath: workspace
          readOnly: true
        - name: snapshot-volume
          mountPath: /watcher/snapshots
        env:
        - name: WATCHER_LOG_LEVEL
          value: "DEBUG"
        - name: WATCHER_API_URL
          value: "http://watcher-backend-service.watcher.svc.cluster.local:3000"
      volumes:
      - name: jcode-vol
        nfs:
          server: "pvc-5ba357bc-eaca-4585-8e2a-a19ff156887b.longhorn-system.svc.cluster.local"
          path: "/pvc-5ba357bc-eaca-4585-8e2a-a19ff156887b"
      - name: snapshot-volume
        persistentVolumeClaim:
          claimName: watcher-code-snapshot-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: watcher-code
  namespace: watcher
  labels:
    app: watcher-code
spec:
  selector:
    app: watcher-code
  ports:
  - name: http-metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: watcher-code-monitor
  namespace: watcher
  labels:
    app: watcher-code
    release: prometheus
spec:
  selector:
    matchLabels:
      app: watcher-code
  namespaceSelector:
    matchNames:
      - watcher
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s