apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: watcher-filemon
  namespace: watcher
spec:
  selector:
    matchLabels:
      app: watcher-filemon
  template:
    metadata:
      labels:
        app: watcher-filemon
    spec:
      containers:
      - name: watcher-filemon
        image: harbor.jbnu.ac.kr/jdevops/watcher-filemon:20250729-1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-metrics
          containerPort: 3000
        volumeMounts:
        - name: jcode-vol
          mountPath: /watcher/codes
          subPath: workspace
          readOnly: true
        - name: snapshot-volume
          mountPath: /watcher/snapshots
        - name: logs-volume
          mountPath: /opt/filemon/logs
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: API_SERVER
          value: "http://watcher-backend-service.watcher.svc.cluster.local:3000"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      imagePullSecrets:
      - name: watcher-harbor-registry-secret
      volumes:
      - name: jcode-vol
        nfs:
          server: "pvc-5ba357bc-eaca-4585-8e2a-a19ff156887b.longhorn-system.svc.cluster.local"
          path: "/pvc-5ba357bc-eaca-4585-8e2a-a19ff156887b"
      - name: snapshot-volume
        persistentVolumeClaim:
          claimName: watcher-filemon-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: watcher-filemon-logs-pvc