apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - daemonset.yaml
  - service.yaml
  - servicemonitor.yaml

commonLabels:
  app: watcher-filemon
  component: filemon

namespace: watcher