apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watcher-filemon-pvc
  namespace: watcher
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watcher-filemon-logs-pvc
  namespace: watcher
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn