apiVersion: v1
kind: Service
metadata:
  name: watcher-filemon
  namespace: watcher
  labels:
    app: watcher-filemon
spec:
  selector:
    app: watcher-filemon
  ports:
  - name: http-metrics
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP