services:
  watcher-filemon:
    build: .
    volumes:
      - /workspace:/watcher/codes:ro # 학생 워크스페이스 마운트
      - ./snapshots:/watcher/snapshots # 스냅샷 저장소 마운트
      - ./app/:/opt/filemon/app/  # 개발시 빠른 코드 변경
      - ./logs:/opt/filemon/logs  # 로그 파일 영구 보존을 위한 호스트 마운트
    ports:
      - 3000:3000 # 메트릭 포트 
    environment:
      - LOG_LEVEL=DEBUG
