apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watcher-code-snapshot-pvc
  namespace: watcher
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn