apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: watcher-filemon
  namespace: watcher
spec:
  selector:
    matchLabels:
      app: watcher-filemon
  template:
    metadata:
      labels:
        app: watcher-filemon
    spec:
      containers:
      - name: watcher-filemon
        image: harbor.jbnu.ac.kr/jdevops/watcher-filemon:20250729-1  # 미리 빌드된 이미지 사용
        imagePullPolicy: IfNotPresent  # 이미지가 존재하지 않을 때만 가져옴
        ports:
        - name: http-metrics
          containerPort: 9090
        volumeMounts:
        - name: jcode-vol
          mountPath: /watcher/codes
          subPath: workspace
          readOnly: true
        - name: snapshot-volume
          mountPath: /watcher/snapshots
        env:
        - name: WATCHER_LOG_LEVEL
          value: "INFO"
        - name: WATCHER_API_URL
          value: "http://watcher-backend-service.watcher.svc.cluster.local:3000"
      imagePullSecrets:
      - name: watcher-harbor-registry-secret
      volumes:
      - name: jcode-vol
        persistentVolumeClaim:
          claimName: jcode-vol-pvc
      - name: snapshot-volume
        persistentVolumeClaim:
          claimName: watcher-filemon-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: watcher-filemon
  namespace: watcher
  labels:
    app: watcher-filemon
spec:
  selector:
    app: watcher-filemon
  ports:
  - name: http-metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: watcher-filemon-monitor
  namespace: watcher
  labels:
    app: watcher-filemon
    release: prometheus
spec:
  selector:
    matchLabels:
      app: watcher-filemon  
  namespaceSelector:
    matchNames:
      - watcher
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
