apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
  namespace: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      containers:
      - name: watcher-code
        image: watcher-code:latest  # 미리 빌드된 이미지 사용
        imagePullPolicy: IfNotPresent  # 이미지가 존재하지 않을 때만 가져옴
        volumeMounts:
        - name: jcode-vol
          mountPath: /watcher/codes
          readOnly: true
        env:
        - name: WATCHER_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: watcher-code-config
              key: WATCHER_LOG_LEVEL
        - name: WATCHER_API_URL
          valueFrom:
            configMapKeyRef:
              name: watcher-code-config
              key: WATCHER_API_URL
        - name: NFS_SERVER
          valueFrom:
            configMapKeyRef:
              name: watcher-code-config
              key: NFS_SERVER
        - name: NFS_PATH
          valueFrom:
            configMapKeyRef:
              name: watcher-code-config
              key: NFS_PATH
      volumes:
      - name: jcode-vol
        nfs:
          server: "$(NFS_SERVER)"
          path: "$(NFS_PATH)"