apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watcher-procmon-logs-pvc
  namespace: watcher
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn