version: '3.8'

services:
  watcher:
    build: .
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    pid: host
    volumes:
      - ./app:/workspace/app
      - /sys/kernel/debug:/sys/kernel/debug:ro
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
      - API_ENDPOINT=http://echo:3000