
services:
  watcher:
    build: .
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN
    pid: host
    ports:
      - "3000:3000"
    volumes:
      - /sys/kernel/debug:/sys/kernel/debug:ro
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
      - API_SERVER=http://localhost:8000