apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watcher-backend-pvc
  namespace: watcher
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn 